### ISSUE TITLE
Running two instances of TorOnionProxy = Cookie Auth file not created

### ISSUE THREAD

**Issue by zeroleak** [thaliproject/Tor_Onion_Proxy_Library#122]
Getting the following error when trying  to start() successively two OnionProxyManager in two separate JavaOnionProxyContext.
It looks like the two instances are conflicting even if they run in distinct install directory.
Any idea?

> java.io.IOException: Cookie Auth file not created: /tmp/torTwo17546824732921432657/lib/tor/control_auth_cookie, len = 0
>         at com.msopentech.thali.toronionproxy.OnionProxyManager.start(OnionProxyManager.java:402) ~[universal-0.0.3.jar!/:na]
>         at com.msopentech.thali.toronionproxy.OnionProxyManager.startWithRepeat(OnionProxyManager.java:131) ~[universal-0.0.3.jar!/:na]
>

**Comment by zeroleak** [comment]
fixed with specifying two different homeDir.
